# Backend Dockerfile for Node.js API
FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
COPY src ./src
COPY images ./images
COPY invoices ./invoices
COPY Procfile ./
COPY README.md ./

RUN npm install --production

EXPOSE 3000

CMD ["node", "src/index.js"]
